import {
  EntityId,
  IsoDate,
  IsoDatetime,
  Username,
  GroupOrPermission,
  Amount,
  Tag,
  AssetSymbol,
  InitiatorKind,
  DocumentSnapshot,
  DfnsError,
  BadRequestError,
  PaymentRequiredError,
  EntityExpiredError,
  EntityNotFoundError,
  DuplicateError,
} from '../Foundations'
import {
  Policy,
  NotifyAndAuditPolicyControl,
  RequestApprovalPolicyControl,
  PolicyRule,
  PolicyControl,
  CreateAmountLimitPrConf,
  UpdateAmountLimitPrConf,
  CreateOutgoingVelocityPrConf,
  CreateSiphoningPrConf,
  SiphoningPrConf,
  UpdateSiphonPrConf,
  AmountLimitPrConf,
  UpdateOutgoingVelocityPrConf,
  OutgoingVelocityPrConf,
  CreateRequestApprovalPcConf,
  UpdateRequestApprovalPcConf,
  CreateNotifyAndAuditPcConf,
  UpdateNotifyAndAuditPcConf,
  AssetAccountSelector,
  PolicyManagementPreferences,
  Create,
  UpdatePolicyRuleInput,
  CreatePolicyInput,
  UpdatePolicyInput,
  CreatePolicyControlInput,
  UpdatePolicyControlInput,
  CreatePolicyRuleInput,
  CreatePolicyRuleConfiguration,
  UpdatePolicyRuleConfiguration,
  UpdatePolicyControlConfiguration,
  CreatePolicyControlConfiguration,
  PolicyRuleConfiguration,
  PolicyActivityKind,
  PolicyStatus,
  PolicyControlKind,
  PolicyRuleKind,
} from './types'

import Aws from 'aws-sdk'
import { getDynamoDbDocumentClient, getEnvParam } from '../utils'
import { compositeValues, createByType, createByGenerator } from '../factories'
